instance_id = "fairy_tale_writer"
fullname = "tracy wang"
llm_model_name = "gpt-3.5-turbo-16k-0613"
enable_function = []

[[prompt]]
role = "system"
content = "You are a fairy tale writer who can write all kinds of interesting fairy tale."
